-- This is an empty migration.

UPDATE "States" SET "stateName" = 'AK' WHERE LOWER("stateName") = LOWER('Alaska');
UPDATE "States" SET "stateName" = 'AL' WHERE LOWER("stateName") = LOWER('Alabama');
UPDATE "States" SET "stateName" = 'AR' WHERE LOWER("stateName") = LOWER('Arkansas');
UPDATE "States" SET "stateName" = 'AZ' WHERE LOWER("stateName") = LOWER('Arizona');
UPDATE "States" SET "stateName" = 'CA' WHERE LOWER("stateName") = LOWER('California');
UPDATE "States" SET "stateName" = 'CO' WHERE LOWER("stateName") = LOWER('Colorado');
UPDATE "States" SET "stateName" = 'CT' WHERE LOWER("stateName") = LOWER('Connecticut');
UPDATE "States" SET "stateName" = 'DC' WHERE LOWER("stateName") = LOWER('District Of Columbia');
UPDATE "States" SET "stateName" = 'DE' WHERE LOWER("stateName") = LOWER('Delaware');
UPDATE "States" SET "stateName" = 'FL' WHERE LOWER("stateName") = LOWER('Florida');
UPDATE "States" SET "stateName" = 'GA' WHERE LOWER("stateName") = LOWER('Georgia');
UPDATE "States" SET "stateName" = 'HI' WHERE LOWER("stateName") = LOWER('Hawaii');
UPDATE "States" SET "stateName" = 'IA' WHERE LOWER("stateName") = LOWER('Iowa');
UPDATE "States" SET "stateName" = 'ID' WHERE LOWER("stateName") = LOWER('Idaho');
UPDATE "States" SET "stateName" = 'IL' WHERE LOWER("stateName") = LOWER('Illinois');
UPDATE "States" SET "stateName" = 'IN' WHERE LOWER("stateName") = LOWER('Indiana');
UPDATE "States" SET "stateName" = 'KS' WHERE LOWER("stateName") = LOWER('Kansas');
UPDATE "States" SET "stateName" = 'KY' WHERE LOWER("stateName") = LOWER('Kentucky');
UPDATE "States" SET "stateName" = 'LA' WHERE LOWER("stateName") = LOWER('Louisiana');
UPDATE "States" SET "stateName" = 'MA' WHERE LOWER("stateName") = LOWER('Massachusetts');
UPDATE "States" SET "stateName" = 'MD' WHERE LOWER("stateName") = LOWER('Maryland');
UPDATE "States" SET "stateName" = 'ME' WHERE LOWER("stateName") = LOWER('Maine');
UPDATE "States" SET "stateName" = 'MI' WHERE LOWER("stateName") = LOWER('Michigan');
UPDATE "States" SET "stateName" = 'MN' WHERE LOWER("stateName") = LOWER('Minnesota');
UPDATE "States" SET "stateName" = 'MO' WHERE LOWER("stateName") = LOWER('Missouri');
UPDATE "States" SET "stateName" = 'MS' WHERE LOWER("stateName") = LOWER('Mississippi');
UPDATE "States" SET "stateName" = 'MT' WHERE LOWER("stateName") = LOWER('Montana');
UPDATE "States" SET "stateName" = 'NC' WHERE LOWER("stateName") = LOWER('North Carolina');
UPDATE "States" SET "stateName" = 'ND' WHERE LOWER("stateName") = LOWER('North Dakota');
UPDATE "States" SET "stateName" = 'NE' WHERE LOWER("stateName") = LOWER('Nebraska');
UPDATE "States" SET "stateName" = 'NH' WHERE LOWER("stateName") = LOWER('New Hampshire');
UPDATE "States" SET "stateName" = 'NJ' WHERE LOWER("stateName") = LOWER('New Jersey');
UPDATE "States" SET "stateName" = 'NM' WHERE LOWER("stateName") = LOWER('New Mexico');
UPDATE "States" SET "stateName" = 'NV' WHERE LOWER("stateName") = LOWER('Nevada');
UPDATE "States" SET "stateName" = 'NY' WHERE LOWER("stateName") = LOWER('New York');
UPDATE "States" SET "stateName" = 'OH' WHERE LOWER("stateName") = LOWER('Ohio');
UPDATE "States" SET "stateName" = 'OK' WHERE LOWER("stateName") = LOWER('Oklahoma');
UPDATE "States" SET "stateName" = 'OR' WHERE LOWER("stateName") = LOWER('Oregon');
UPDATE "States" SET "stateName" = 'PA' WHERE LOWER("stateName") = LOWER('Pennsylvania');
UPDATE "States" SET "stateName" = 'RI' WHERE LOWER("stateName") = LOWER('Rhode Island');
UPDATE "States" SET "stateName" = 'SC' WHERE LOWER("stateName") = LOWER('South Carolina');
UPDATE "States" SET "stateName" = 'SD' WHERE LOWER("stateName") = LOWER('South Dakota');
UPDATE "States" SET "stateName" = 'TN' WHERE LOWER("stateName") = LOWER('Tennessee');
UPDATE "States" SET "stateName" = 'TX' WHERE LOWER("stateName") = LOWER('Texas');
UPDATE "States" SET "stateName" = 'UT' WHERE LOWER("stateName") = LOWER('Utah');
UPDATE "States" SET "stateName" = 'VA' WHERE LOWER("stateName") = LOWER('Virginia');
UPDATE "States" SET "stateName" = 'VT' WHERE LOWER("stateName") = LOWER('Vermont');
UPDATE "States" SET "stateName" = 'WA' WHERE LOWER("stateName") = LOWER('Washington');
UPDATE "States" SET "stateName" = 'WI' WHERE LOWER("stateName") = LOWER('Wisconsin');
UPDATE "States" SET "stateName" = 'WV' WHERE LOWER("stateName") = LOWER('West Virginia');
UPDATE "States" SET "stateName" = 'WY' WHERE LOWER("stateName") = LOWER('Wyoming');
UPDATE "States" SET "stateName" = 'PR' WHERE LOWER("stateName") = LOWER('Puerto Rico');
UPDATE "States" SET "stateName" = 'GU' WHERE LOWER("stateName") = LOWER('Guam');
UPDATE "States" SET "stateName" = 'AS' WHERE LOWER("stateName") = LOWER('American Samoa');
UPDATE "States" SET "stateName" = 'VI' WHERE LOWER("stateName") = LOWER('U.S. Virgin Islands');
UPDATE "States" SET "stateName" = 'MP' WHERE LOWER("stateName") = LOWER('Northern Mariana Islands');
UPDATE "States" SET "stateName" = 'AA' WHERE LOWER("stateName") = LOWER('Armed Forces Americas');
UPDATE "States" SET "stateName" = 'AE' WHERE LOWER("stateName") = LOWER('Armed Forces Europe');
UPDATE "States" SET "stateName" = 'AP' WHERE LOWER("stateName") = LOWER('Armed Forces Pacific');