ARG PLATFORM=linux/arm64
FROM --platform=$BUILDPLATFORM node:lts-alpine

# Install OpenSSL and other required dependencies
RUN apk add --no-cache openssl

# Set the environment
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# Set the working directory
WORKDIR /usr/src/app

# Copy package files and Prisma schema
COPY package*.json ./
COPY yarn.lock .
COPY tsconfig.json ./
COPY prisma ./prisma/

# Install dependencies
RUN yarn install  

# Copy the rest of the application files
COPY . .

# Set permissions for the node user
RUN chown -R node /usr/src/app

# Use the node user to run the application
USER node

# Increase Node.js memory limit and run the build
ENV NODE_OPTIONS="--max-old-space-size=4096"
ENV DATABASE_URL=${DATABASE_URL}
ENV SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL}

# Run Prisma generate and build the app
RUN yarn prisma:generate && yarn build

# Start the application
CMD ["yarn", "docker-start:background-jobs"]
